### ISSUE TITLE
An error occurred while processing a request in Rasa Skill 

### ISSUE THREAD

**Issue by praypratyay** [jamesmf/skill-rasa-chat#1]
**On mycroft  side the error is:**
 
Traceback (most recent call last):
~~~~t-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
~~~~/skills/skill-rasa-chat/__init__.py", line 43, in handle_talk_to_rasa_intent
    messages = self.get_rasa_response(response)
~~~~/mycroft/skills/skill-rasa-chat/__init__.py", line 112, in get_rasa_response
    messages = self.hit_rasa(utterance)
  File "/opt/mycroft/skills/skill-rasa-chat/__init__.py", line 129, in hit_rasa
r  esponse = requests.post(self.predict_endpoint).json()
~~~~ore/.venv/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


**and on RASA side the error is:**

2020-08-09 03:28:59 INFO     root  - Rasa server is up and running.
Exception occurred while handling uri: 'http://localhost:5005/conversations/mycroft_user/messages?include_events=NONE'
Traceback (most recent call last):
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /conversations/mycroft_user/messages not found
Exception occurred while handling uri: 'http://localhost:5005/conversations/mycroft_user/predict'
Traceback (most recent call last):
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /conversations/mycroft_user/predict not found



Can you tell me in detail the steps for integrating rasa with mycroft and where i am getting the error?

**Comment by praypratyay** [comment]
Also, Why is post method not allowed for the rasa URL

Traceback (most recent call last):
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 452, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method POST not allowed for URL /
Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/home/pratyay/Desktop/CHAT/lib/python3.6/site-packages/sanic/router.py", line 452, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method POST not allowed for URL /
